#!/usr/bin/env python
"""
WordAPI.py
Copyright 2012 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class TaskApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def GetTask(self, **kwargs):
        """Get a list of tasks

        Args:
            task_name, str:  (optional)
            git_repo, str:  (optional)
            git_commit, str:  (optional)
            latest, str:  (optional)
            
        Returns: ReturnTaskBriefListSchema
        """

        allParams = ['task_name', 'git_repo', 'git_commit', 'latest']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method GetTask" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/task/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('task_name' in params):
            queryParams['task_name'] = self.apiClient.toStringValue(params['task_name'])
        if ('git_repo' in params):
            queryParams['git_repo'] = self.apiClient.toStringValue(params['git_repo'])
        if ('git_commit' in params):
            queryParams['git_commit'] = self.apiClient.toStringValue(params['git_commit'])
        if ('latest' in params):
            queryParams['latest'] = self.apiClient.toStringValue(params['latest'])
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ReturnTaskBriefListSchema')
        return responseObject
        
        
    def PostTask(self, body, **kwargs):
        """Post a new task

        Args:
            body, PostTaskSchema:  (required)
            
        Returns: PostTaskSchemaReturn
        """

        allParams = ['body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method PostTask" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/task/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'PostTaskSchemaReturn')
        return responseObject
        
        
    def GetTaskArg(self, task_id, **kwargs):
        """Get all info regarding a task

        Args:
            task_id, str:  (required)
            
        Returns: ReturnTaskSchema
        """

        allParams = ['task_id']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method GetTaskArg" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/task/{task_id}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('task_id' in params):
            replacement = str(self.apiClient.toPathValue(params['task_id']))
            resourcePath = resourcePath.replace('{' + 'task_id' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ReturnTaskSchema')
        return responseObject
        
        
    def PutTask(self, task_id, body, **kwargs):
        """Update an existing task

        Args:
            task_id, str:  (required)
            body, ReturnTaskSchema:  (required)
            
        Returns: null
        """

        allParams = ['task_id', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method PutTask" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/task/{task_id}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}

        if ('task_id' in params):
            replacement = str(self.apiClient.toPathValue(params['task_id']))
            resourcePath = resourcePath.replace('{' + 'task_id' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'null')
        return responseObject
        
        
    


