#!/usr/bin/env python
"""
WordAPI.py
Copyright 2012 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class TaskbyparamApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def GetTasks(self, mime_type, **kwargs):
        """Get a list of tasks by accepted parameter mimetype

        Args:
            mime_type, str:  (required)
            latest, str:  (optional)
            
        Returns: ReturnTaskBriefListSchema
        """

        allParams = ['mime_type', 'latest']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method GetTasks" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/taskbyparam/{mime_type}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('latest' in params):
            queryParams['latest'] = self.apiClient.toStringValue(params['latest'])
        if ('mime_type' in params):
            replacement = str(self.apiClient.toPathValue(params['mime_type']))
            resourcePath = resourcePath.replace('{' + 'mime_type' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ReturnTaskBriefListSchema')
        return responseObject
        
        
    


