#!/usr/bin/env python
"""
WordAPI.py
Copyright 2012 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class FileApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    def create_file(self, body, **kwargs):
        """Creates a file with attributes provided in request body

        Args:
            body, FilePostJson:  (required)
            
        Returns: EntityReturn
        """

        allParams = ['body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method create_file" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'EntityReturn')
        return responseObject
        
        
    def delete_file(self, uuid, **kwargs):
        """Delete a file

        Args:
            uuid, str:  (required)
            
        Returns: StatusReturn
        """

        allParams = ['uuid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method delete_file" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'StatusReturn')
        return responseObject
        
        
    def get_file(self, uuid, **kwargs):
        """Get a file

        Args:
            uuid, str:  (required)
            
        Returns: EntityReturn
        """

        allParams = ['uuid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method get_file" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'EntityReturn')
        return responseObject
        
        
    def update_file(self, uuid, body, **kwargs):
        """Updates a file with attributes provided in request body

        Args:
            uuid, str:  (required)
            body, FilePutJson:  (required)
            
        Returns: EntityReturn
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update_file" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'EntityReturn')
        return responseObject
        
        
    def remove_acl(self, uuid, body, **kwargs):
        """Remove an entity acl

        Args:
            uuid, str:  (required)
            body, ACLDeleteJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method remove_acl" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/acl'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def get_acl(self, uuid, **kwargs):
        """Get all acl of an entity

        Args:
            uuid, str:  (required)
            
        Returns: dict
        """

        allParams = ['uuid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method get_acl" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/acl'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def add_acl(self, uuid, body, **kwargs):
        """Add acl to an entity

        Args:
            uuid, str:  (required)
            body, ACLJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method add_acl" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/acl'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def update_acl(self, uuid, body, **kwargs):
        """Update an entity acl

        Args:
            uuid, str:  (required)
            body, ACLJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update_acl" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/acl'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def get_file_content(self, uuid, **kwargs):
        """Get a file content

        Args:
            uuid, str:  (required)
            
        Returns: str
        """

        allParams = ['uuid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method get_file_content" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/content'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        
        
    def remove_metadata(self, uuid, body, **kwargs):
        """Remove an entity metadata

        Args:
            uuid, str:  (required)
            body, MetadataDeleteJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method remove_metadata" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/metadata'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def get_metadata(self, uuid, **kwargs):
        """Get all metadata of an entity

        Args:
            uuid, str:  (required)
            
        Returns: dict
        """

        allParams = ['uuid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method get_metadata" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/metadata'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def add_metadata(self, uuid, body, **kwargs):
        """Add metadata to an entity

        Args:
            uuid, str:  (required)
            body, MetadataJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method add_metadata" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/metadata'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    def update_metadata(self, uuid, body, **kwargs):
        """Update an entity metadata

        Args:
            uuid, str:  (required)
            body, MetadataJson:  (required)
            
        Returns: dict
        """

        allParams = ['uuid', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method update_metadata" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/file/{uuid}/metadata'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}

        if ('uuid' in params):
            replacement = str(self.apiClient.toPathValue(params['uuid']))
            resourcePath = resourcePath.replace('{' + 'uuid' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'dict')
        return responseObject
        
        
    


