#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class ReturnJobListAtomSchema:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'job_id': 'str',
            'job_name': 'str',
            'task_id': 'str',
            'state': 'str',
            'finish_reason': 'str',
            'user': 'str',
            'last_contact': 'str',
            'start_time': 'str',
            'queue_job_id': 'str',
            'queue_name': 'str'

        }


        #uuid of the job
        self.job_id = None # str
        #name of the job
        self.job_name = None # str
        #uuid of the task
        self.task_id = None # str
        #Current state of the job
        self.state = None # str
        #How the job ended
        self.finish_reason = None # str
        #Name of the user who started the job
        self.user = None # str
        #Time of last contact in ISO 8601 format
        self.last_contact = None # str
        #Time of last contact in ISO 8601 format
        self.start_time = None # str
        #Identifier of the job in the remote queue
        self.queue_job_id = None # str
        #Identifier of the remote queue
        self.queue_name = None # str
        
