#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class TaskRequirements:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'base_env': 'str',
            'customizations': 'TaskCustomizations',
            'env_vars': 'object',
            'file_filters': 'object'

        }


        #Base environment
        self.base_env = None # str
        self.customizations = None # TaskCustomizations
        #Environment variables
        self.env_vars = None # object
        #Filters for file output list
        self.file_filters = None # object
        
