#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class TaskProperties:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'task_name': 'str',
            'full_name': 'str',
            'caption': 'str',
            'state': 'str',
            'categories': 'list[str]',
            'accepts': 'list[object]',
            'returns': 'list[object]',
            'compatible_queues': 'list[object]',
            'description': 'str',
            'author': 'str'

        }


        #System Name for the task
        self.task_name = None # str
        #Human-friendly short name for the task
        self.full_name = None # str
        #Short description of task
        self.caption = None # str
        #Current state of the task
        self.state = None # str
        #List of categories
        self.categories = None # list[str]
        #List of parameter types
        self.accepts = None # list[object]
        #List of return types
        self.returns = None # list[object]
        #List of compatible remote queues
        self.compatible_queues = None # list[object]
        #Description of task
        self.description = None # str
        #Author of task
        self.author = None # str
        
