# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboratory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorycontext',
            name='xkcd_num',
            field=models.IntegerField(default=1),
        ),
    ]
