#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class EntityReturn:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            '_createdBy': 'str',
            '_createdOn': 'str',
            '_contentType': 'str',
            '_description': 'str',
            '_parent': 'str',
            '_uuid': 'str',
            '_entityType': 'str',
            '_contentUri': 'str',
            '_name': 'str'

        }


        #Entity creator userid
        self._createdBy = None # str
        #Entity creation time
        self._createdOn = None # str
        #Content type of the entity
        self._contentType = None # str
        #Short description of the entity
        self._description = None # str
        #UUID of the parent
        self._parent = None # str
        #UUID of the entity
        self._uuid = None # str
        #Type of the entity
        self._entityType = None # str
        #External uri to entity content
        self._contentUri = None # str
        #Name of the entity
        self._name = None # str
        
