#!/usr/bin/env python
"""
Copyright 2012 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class FilePostJson:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            '_parent': 'str',
            '_contentType': 'str',
            '_description': 'str',
            '_contentUri': 'str',
            '_name': 'str'

        }


        #Parent entity's UUID
        self._parent = None # str
        #The kind of content that one might expect here
        self._contentType = None # str
        #Short description of the file
        self._description = None # str
        #External uri to entity content
        self._contentUri = None # str
        #Name of the file
        self._name = None # str
        
